import MainTransaction from "components/MainTransaction";
import Sidebar from "components/Sidebar";
import Head from "next/head";
import React, { useState } from "react";

export default function Home() {
  const [tabActive, setTabActive] = useState(0);

  const CBsetActive = (selected) => {
    setTabActive(selected);
  };

  return (
    <div>
      <Head>
        <title>Test RTI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar tabActive={tabActive} setTabActive={CBsetActive} />
      <div className="w-4/5 float-right min-h-screen pb-10 bg-sky-100">
        {tabActive == 0 && <MainTransaction />}
      </div>
    </div>
  );
}
