import MainContent from "components/MainContent";
import Sidebar from "components/Sidebar";
import Head from "next/head";
import React, { useState } from "react";

export default function Home() {
  const [tabActive, setTabActive] = useState(1);

  const CBsetActive = (selected) => {
    setTabActive(selected);
  };

  return (
    <div>
      <Head>
        <title>Test RTI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar tabActive={tabActive} setTabActive={CBsetActive} />
      <MainContent tabActive={tabActive} />
    </div>
  );
}
